/** Generated by scripts/bake-figma-screen-ui.mjs — do not edit */
export const SCREEN_NOTIFICATION_AVATER_META = {
  "width": 185,
  "height": 32,
  "background": "#ffffff",
  "screenId": "screen_notification_avater",
  "figmaRenderedAt": "2026-06-08T07:56:30.535Z"
} as const;
