import React from "react";
import { Button as UiButton } from "@lab/ui";

/**
 * Semantic React delivery — @lab/ui components (ingress: storybook).
 * Regenerated by story-package semantic emitter.
 */
export function Button() {
  return (
    <UiButton
    variant="primary"
    children="Primary"
  />
  );
}
