/** Generated by scripts/bake-figma-screen-ui.mjs — do not edit */
export const SCREEN1_META = {
  "width": 1921,
  "height": 937,
  "background": "#ffffff",
  "screenId": "screen_1",
  "figmaRenderedAt": "2026-06-08T10:17:31.517Z"
} as const;
