/** Generated by scripts/bake-figma-screen-ui.mjs — do not edit */
export const DIALOG_META = {
  "width": 709,
  "height": 288,
  "background": "#ffffff",
  "screenId": "screen_dialog_buttons",
  "figmaRenderedAt": "2026-06-08T17:35:06.165Z"
} as const;
