/** Generated by scripts/bake-figma-screen-ui.mjs — do not edit */
export const SCREEN2_META = {
  "width": 3842,
  "height": 1874,
  "background": "#ffffff",
  "screenId": "screen_2",
  "figmaRenderedAt": "2026-06-08T07:56:30.313Z"
} as const;
